#!/bin/sh

export MANPAGER="less -R --use-color -Dd+r -Du+b"

# list files
alias ls="eza -laF --icons --time modified --time-style long-iso --sort name --group-directories-first --git"
alias ll="exa -a --icons --sort name --group-directories-first"  # grid format
alias lt="exa -T --icons --sort name --group-directories-first" # tree format

alias grep="grep --color=auto"

# confirm before overwriting something
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

# pacman / paru
alias orphans="pacman -Qdtq"
alias remove-orphans="pacman -Qdtq | sudo pacman -Rns -"
alias clear-cache="paru -Scc"

# git
alias g="git"
alias gs="git status"
alias ga="git commit -a"

# flutter
alias fget="flutter pub get"
alias frun="dart run build_runner build --delete-conflicting-outputs"
alias fwatch="dart run build_runner watch --delete-conflicting-outputs"

# misc
alias dotfiles="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
alias untar="tar -xf"
alias vscodium="vscodium --ozone-platform=wayland"
alias codium="codium --ozone-platform=wayland"
